# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Danilo Heller Prates
email: daniloprates@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Senior Front End Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: SBootstrap
github_username:  BlackrockDigital
facebook_username: StartBootstrap

# Address information
address_street: Rua Sud Mennucci, 124
address_city: Sao Paulo
address_state: SP
address_zip: 04017-080

# Build settings
markdown: kramdown


## CV SETTINGS


# Site settings
cv-title: Danilo Prates
cv-email: daniloprates@gmail.com
cv-description: > # this means to ignore newlines until "baseurl:"
    Senior Front End Developer
cv-baseurl: "" # the subpath of your site, e.g. /blog
cv-url: "http://yourdomain.com" # the base hostname & protocol for your site

