# Site settings
title: Danilo Heller Prates
email: daniloprates@gmail.com
url: https://daniloprates.github.io
description: "Senior Front End Developer"
skills: "Front End Developer"
meta_author: Prates Danilo

collections:
  general:
  work:
  projects:
    output: true

defaults:
  -
    values:
      layout: "single"

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: daniloprates

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 59C1E2 #80B3FF
  primary-rgb: "89,193,226" #"128,179,255"
  secondary: 8B5279 #FD6E8A
  secondary-dark: 951E4E #A2122F

# color:
#   primary: 18bc9c #80B3FF
#   primary-rgb: "24,288,156" #"128,179,255"
#   secondary: 2c3e50 #FD6E8A
#   secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Danilo Prates
  location: Sao Paulo - Brazil
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/dvnilo
  - title: facebook
    url: http://facebook.com/daniloprates
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/daniloprates
  - title: github
    url: http://github.com/daniloprates

# Postal address (add as many lines as necessary)
address:
  - line: Rua Sud Mennucci, 124
  - line: Sao Paulo


# Build settings
markdown: kramdown
permalink: pretty



## CV SETTINGS


# Site settings
cv-title: Danilo Prates
cv-email: daniloprates@gmail.com
cv-description: > # this means to ignore newlines until "baseurl:"
    Senior Front End Developer
cv-baseurl: "" # the subpath of your site, e.g. /blog
cv-url: "http://yourdomain.com" # the base hostname & protocol for your site


